name: zjyun-brain
swagger:
  enable: true
server:
  port: 8080
spring:
  datasource:
    url:  jdbc:mysql://192.168.22.25:3308/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
